Skip hdtbl and mom tests if needed config is missing.
* contrib/hdtbl/examples/test-hdtbl.sh.in: exit 77 (indicates
automake to skip the result) if 'gs' is missing.

* contrib/hdtbl/hdtbl.am: flag correctly test program generation.

* contrib/mom/examples/test-mom.sh.in: exit 77 if URW fonts are
not available.

* contrib/mom/mom.am: distribute inconditionnally test-mom.in.

* m4/groff.m4 (GROFF_URW_FONTS): check if 'awk' and 'gs' are
available, and replace non-portable 'grep' command by awk script.

diff --git a/contrib/hdtbl/examples/test-hdtbl.sh.in b/contrib/hdtbl/examples/test-hdtbl.sh.in
--- a/contrib/hdtbl/examples/test-hdtbl.sh.in
+++ b/contrib/hdtbl/examples/test-hdtbl.sh.in
@@ -24,6 +24,12 @@
 builddir="@abs_top_builddir@"
 gs_program="@GHOSTSCRIPT@"
 ret=0
+
+if test "$gs_program" = "missing"; then
+   echo "ghostscript program missing, can't check hdtbl examples"
+   exit 77
+fi
+
 # $1 file, $2 expected number of pages
 check_number_pages()
 {
diff --git a/contrib/mom/examples/test-mom.sh.in b/contrib/mom/examples/test-mom.sh.in
--- a/contrib/mom/examples/test-mom.sh.in
+++ b/contrib/mom/examples/test-mom.sh.in
@@ -19,6 +19,7 @@
 #
 
 builddir="@abs_top_builddir@"
+have_urw_fonts="@groff_have_urw_fonts@"
 examplesdir="$builddir/contrib/mom/examples"
 ret=0
 list="
@@ -29,6 +30,12 @@ list="
   slide-demo.pdf
   typesetting.pdf
   "
+
+if test "$have_urw_fonts" != "yes"; then
+    echo "No URW fonts, mom examples cannot be correctly generated"
+    exit 77
+fi
+
 # $1: pdf file
 # $2: expected number of pages
 check_number_pages()
